### ISSUE TITLE
[Save Command] Saving into 2 location instead of one

### ISSUE THREAD

**Issue by marcusngwenjian** [CS2103AUG2016-W15-C3/main#106]
To be clarified with Akshay the requirement of saving data.
### Possibility One:

Saving data into both old and new location
### Possibility Two:

Saving data into new location, but retain old copy in the old location and update both location
### Possibility Three:

Saving data into new location, but retain old copy in the old location but only update new location
### Possibility Four:

Saving data into new location AND delete old copy from old location

**Comment by turtle96** [comment]
Current implementation is option 2
