### ISSUE TITLE
Add command does not reject invalid date

### ISSUE THREAD

**Issue by turtle96** [CS2103AUG2016-W15-C3/main#146]
add smth else on 50-april

![image](https://cloud.githubusercontent.com/assets/16895138/19773442/2d676aee-9c9c-11e6-8eca-7ab2b1655b87.png)

might be good to feedback to user the date is invalid i.e. user typed date wrongly

**Comment by marcusngwenjian** [comment]
@turtle96 
No, this is our way of handling user input. We do not throw error message at them, but rather, handled it as a description. This is because 
1. Throwing too many error messages will annoy the user
2. Some user may not intend 50-april to be a date
