### ISSUE TITLE
invalid command format?

### ISSUE THREAD

**Issue by turtle96** [CS2103AUG2016-W15-C3/main#160]
Is this a bug or command format is invalid, and in what way?
![image](https://cloud.githubusercontent.com/assets/16895138/19836664/5b7c8426-9ee2-11e6-9dc6-89493b30bacb.png)

**Comment by marcusngwenjian** [comment]
@turtle96 
This is not a bug. 

## Actual

StartDate: today
EndDate: tmr
StartTime: 3pm
EndTime: 6pm

## Intention

add this by tmr, from around 3pm to 6pm

<br>
In english sense, it does not make sense. Using the word by suggest a deadline. A deadline does not have 2 dates nor 2 timings. Hence, this is not a bug.
