### ISSUE TITLE
[Save Command] File and directory names to avoid for windows and linux

### ISSUE THREAD

**Issue by marcusngwenjian** [CS2103AUG2016-W15-C3/main#215]
![image](https://cloud.githubusercontent.com/assets/13817632/19954024/1465a23c-a1af-11e6-96ef-0f50996f45db.png)
Figure 1. Symbols to avoid for linux file naming
<br>
![image](https://cloud.githubusercontent.com/assets/13817632/19954031/31017f74-a1af-11e6-89aa-6838e877d8c2.png)
Figure 2. Symbols to avoid for window file naming
<br>

We should not allow them to use all of these symbols so that it can work on both windows and linux environment (Which we guaranteed the user that our application will work in both operating systems in the user guide)

**Comment by marcusngwenjian** [comment]
"/" and "&" is still able to being saved as a directory name, which is not allowed in linux.
Please fix

**Comment by turtle96** [comment]
@marcusngwj "&" is allowed because it is run on windows, the rejection occurs via file writing exceptions, since the symbol is acceptable for windows, it wont reject it. As for "/", it does reject the symbol

pls close this issue after reading

**Comment by marcusngwenjian** [comment]
@turtle96 I understand that it is allowed on windows, however, it is not allowed on the linux machine. Kindly revise.

**Comment by turtle96** [comment]
@marcusngwj As it rejects via file writing exceptions, on linux it will reject the necessary symbols. If you insist on it rejecting "&" for windows too then I will code it later. Just saying, it's not very fair to users of windows that they can't use "&"

please inform me of your final decision when you hv read this

**Comment by marcusngwenjian** [comment]
@turtle96 To clarify, it is machine-dependent? If it is, the current code is fine. 
Close this issue.
