### ISSUE TITLE
[Undo Command] Deletes previous edit command

### ISSUE THREAD

**Issue by marcusngwenjian** [CS2103AUG2016-W15-C3/main#221]
![image](https://cloud.githubusercontent.com/assets/13817632/19977950/5343f342-a230-11e6-8cd4-74f857d7a742.png)
Figure 1. After adding task
<br>
![image](https://cloud.githubusercontent.com/assets/13817632/19978016/6fcb1cf2-a230-11e6-95e6-4368ccb3d90a.png)
Figure 2. Execute edit command
<br>
![image](https://cloud.githubusercontent.com/assets/13817632/19977926/3de178c6-a230-11e6-9c25-8775320c350f.png)
Figure 3. Edit command removes add command in command history

**Comment by turtle96** [comment]
@marcusngwj this is a fix for a bug zhuolin found, if task "first" is edited to "second", undoing "add first" will do nothing since the task has been changed to "second", therefore there will be nothing to delete.

Please close this issue after reading.
