### ISSUE TITLE
Feedback for dev guide

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2016-W15-C3/main#277]
Incorrect SD notation

![image](https://cloud.githubusercontent.com/assets/1673303/20590662/760fef04-b25f-11e6-9e50-ea6c587216f0.png)

**Comment by marcusngwenjian** [comment]
![image](https://cloud.githubusercontent.com/assets/13817632/20637320/6dbb34e2-b3bf-11e6-8095-509b367a0ec1.png)
Correction to SD

**Comment by damithc** [comment]
Looks good. 👍 
Regarding `alt`, it should be the bottom right corner that is cut off, not the top right corner.
