### ISSUE TITLE
Bug found in undo that add invalid action into undo history

### ISSUE THREAD

**Issue by marcusngwenjian** [CS2103AUG2016-W15-C3/main#98]
![image](https://cloud.githubusercontent.com/assets/13817632/19630664/7bfc1ac0-99c1-11e6-9731-a180177c0877.png)
Figure 1. Attempt to add invalid date (Failed attempt)
<br>
![image](https://cloud.githubusercontent.com/assets/13817632/19630694/4a4beed2-99c2-11e6-925b-a970d18fd807.png)
Figure 2. Attempt to delete invalid index (Failed attempt)
<br>
![image](https://cloud.githubusercontent.com/assets/13817632/19636726/c15858ae-99fd-11e6-90bf-9aeb62709e5d.png)
Figure 3. Invalid command reflected in list-undo

**Comment by turtle96** [comment]
closed by Implement undo for add and delete and edit (list of commands support) #97
